version: '3.8'

services:
  oracle:
    image: oracle/database:19c
    container_name: oracle-db
    environment:
      - ORACLE_PWD=mysecretpassword
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - oracle-network

volumes:
  oracle-data:

networks:
  oracle-network:

