version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/express:21c
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=your_password
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
