version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-free
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - oracle-data:/u01/app/oracle

volumes:
  oracle-data:
