# Use Oracle Linux 8 as base image
FROM oraclelinux:8

# Install Oracle Database prerequisites
RUN yum -y install oracle-database-preinstall-21c

# Set environment variables
ENV ORACLE_HOME=/opt/oracle/product/21c/dbhome_1
ENV PATH=$PATH:$ORACLE_HOME/bin

# Expose necessary ports
EXPOSE 1521

# Copy the necessary scripts or configurations if required
COPY ./scripts/*.sh /opt/oracle/scripts/

# Tornar o script executável
RUN chmod +x /opt/oracle/scripts/*.sh

# Run Oracle Database setup and start the database
CMD ["/opt/oracle/product/21c/dbhome_1/network/admin/tnsnames.ora"]
